version: 2.1

orbs:
  python: circleci/python@1.3.2




workflows:
  my_workflow:  # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    # For more details on extending your workflow, see the configuration docs: https://circleci.com/docs/2.0/configuration-reference/#workflows
    jobs:
      - build-and-test

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.8

        environment:
          # This URL is configured from the environment variables set below


    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: pytest 

  deploy_application:
    docker:
      - image: cimg/python:3.8
    
    steps:
      - checkout
      - run:
          name: Deploying deploy_application
          command: echo "Deploying app now..."
        


